services:
    Ruta.RutaController:
        class: TesisBuscadorBundle\Controller\ServiceRoutingController
#    tesis_buscador.example:
#        class: Tesis\BuscadorBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
